/* Generated by AN DISI Unibo */ 
package it.unibo.workerinroom

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Workerinroom ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		var mapEmpty    = false
		val mapname     = "roomMbotWithTable" //yyy "roomMapWithTable"
		
		var Curmove     = "" 
		var curmoveIsForward = false 
		
		//REAL ROBOT
		//var StepTime   = 1000 	 
		//var PauseTime  = 500 
		
		//VIRTUAL ROBOT
		var StepTime   = 380		//for virtual // modificato era a 330
		var PauseTime  = 500
		
		var PauseTimeL  = PauseTime.toLong()
		
		var timePreStep = 1L // per calcolo time backstep
		var crashCounter = 0 // per riprovare a muoversi avanti supponendo ostacolo mobile
		var timeBack = -1 // tempo di backstep
		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('moves.pl')","") //set resVar	
						itunibo.coap.client.resourceObserverCoapClient.create( "coap://localhost:5683/resourcemodel"  )
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.moveUtils.loadRoomMap(myself ,mapname )
						itunibo.planner.moveUtils.showCurrentRobotState(  )
							val MapStr =  itunibo.planner.plannerUtil.getMapOneLine()  
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
						println("&&&  workerinroom STARTED")
					}
					 transition(edgeName="t016",targetState="setGoalAndDo",cond=whenDispatch("moveButlerTo"))
				}	 
				state("setGoalAndDo") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moveButlerTo(X,Y,D)"), Term.createTerm("moveButlerTo(X,Y,D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								storeCurrentMessageForReply()
								itunibo.planner.plannerUtil.setGoal( payloadArg(0), payloadArg(1)  )
								itunibo.planner.moveUtils.doPlan(myself)
						}
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("executePlannedActions") { //this:State
					action { //it:State
						solve("retract(move(M))","") //set resVar	
						if(currentSolution.isSuccess()) { Curmove = getCurSol("M").toString() 
						              curmoveIsForward=(Curmove == "w")
						 }
						else
						{ Curmove = ""; curmoveIsForward=false
						 }
					}
					 transition( edgeName="goto",targetState="checkAndDoAction", cond=doswitchGuarded({(Curmove.length>0) }) )
					transition( edgeName="goto",targetState="goalOk", cond=doswitchGuarded({! (Curmove.length>0) }) )
				}	 
				state("goalOk") { //this:State
					action { //it:State
							val MapStr =  itunibo.planner.plannerUtil.getMapOneLine()  
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
						replyToCaller("goalReached", "goalReached(ok)")
					}
					 transition(edgeName="t017",targetState="setGoalAndDo",cond=whenDispatch("moveButlerTo"))
				}	 
				state("checkAndDoAction") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="doForwardMove", cond=doswitchGuarded({curmoveIsForward}) )
					transition( edgeName="goto",targetState="doTheMove", cond=doswitchGuarded({! curmoveIsForward}) )
				}	 
				state("doTheMove") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.rotate(myself ,Curmove, PauseTime )
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("doForwardMove") { //this:State
					action { //it:State
						delay(PauseTimeL)
						itunibo.planner.moveUtils.attemptTomoveAhead(myself ,StepTime )
						timePreStep = System.currentTimeMillis()
					}
					 transition(edgeName="t018",targetState="handleStopAppl",cond=whenEvent("stopAppl"))
					transition(edgeName="t019",targetState="handleStepOk",cond=whenDispatch("stepOk"))
					transition(edgeName="t020",targetState="hadleStepFail",cond=whenDispatch("stepFail"))
				}	 
				state("handleStopAppl") { //this:State
					action { //it:State
						println("APPLICATION STOPPED. Waiting for a reactivate")
					}
					 transition(edgeName="t021",targetState="handleReactivateAppl",cond=whenEvent("reactivateAppl"))
				}	 
				state("handleReactivateAppl") { //this:State
					action { //it:State
						println("APPLICATION RESUMED")
					}
					 transition(edgeName="t022",targetState="handleStepOk",cond=whenDispatch("stepOk"))
					transition(edgeName="t023",targetState="hadleStepFail",cond=whenDispatch("stepFail"))
				}	 
				state("handleStepOk") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.updateMapAfterAheadOk(myself)
						crashCounter = 0
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("hadleStepFail") { //this:State
					action { //it:State
						if(crashCounter == 0){ println("timeBack fatto da noi")
						timeBack = (System.currentTimeMillis() - timePreStep - 45).toInt()
						println("timeBack = $timeBack")
						 }
						crashCounter++
						itunibo.planner.moveUtils.backToCompensate(myself ,timeBack, 0 )
						if((crashCounter > 1)){ println("Static obstacle found!")
						val ButlerDirection = itunibo.planner.moveUtils.getDirection(myself)
						println("ButlerDirection = $ButlerDirection")
						println("Updating map with the static obstacle just found")
						itunibo.planner.moveUtils.setObstacleOnCurrentDirection(myself)
						println("New map")
						itunibo.planner.moveUtils.showCurrentRobotState(  )
						println("Updating plan")
						solve("retractall(move(_))","") //set resVar	
						itunibo.planner.moveUtils.doPlan(myself)
						crashCounter = 0
						 }
						else
						 { println("Found obstacle, supposedly a moving one")
						 var timesLeft = 2 - crashCounter
						 println("Trying to move ahead other $timesLeft times")
						 delay(2000) 
						 solve("asserta(move(w))","") //set resVar	
						  }
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
			}
		}
}
