/* Generated by AN DISI Unibo */ 
package it.unibo.pantry

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Pantry ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("&&& pantry STARTED")
						solve("consult('pantryInit.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="showStateTask", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("&&& pantry waiting for command")
					}
					 transition(edgeName="t02",targetState="showStateTask",cond=whenDispatch("showState"))
					transition(edgeName="t03",targetState="getTask",cond=whenDispatch("get"))
					transition(edgeName="t04",targetState="putTask",cond=whenDispatch("put"))
				}	 
				state("showStateTask") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						solve("getPantryState(L)","") //set resVar	
						if(currentSolution.isSuccess()) { 
										val PantryState = itunibo.prolog.prologUtils.parseTablewareState(myself, "L")
						emit("modelcontent", "modelcontent(content(pantry(state($PantryState))))" ) 
						 }
						else
						{ println("getPantryState FAIL")
						 }
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("getTask") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("get(ARG)"), Term.createTerm("get(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								val Tableware = payloadArg(0)
								solve("removeTablewareList($Tableware)","") //set resVar	
								if(currentSolution.isSuccess()) { forward("put", "put($Tableware)" ,"butlermind" ) 
								 }
								else
								{ println("pantryGet FAIL")
								 }
						}
					}
					 transition( edgeName="goto",targetState="showStateTask", cond=doswitch() )
				}	 
				state("putTask") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("get(ARG)"), Term.createTerm("get(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								val Tableware = payloadArg(0)
								solve("addTablewareList($Tableware)","") //set resVar	
								if(currentSolution.isSuccess()) { forward("remove", "remove($Tableware)" ,"butlermind" ) 
								 }
								else
								{ println("pantryPut FAIL")
								 }
						}
					}
					 transition( edgeName="goto",targetState="showStateTask", cond=doswitch() )
				}	 
			}
		}
}
