/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDummyWorkInRoom
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "workinroomhost", this, "roomelements.pl", "sysRules.pl"
	)
}

